import React from "react";

const CartPic = () => {
  return (
    <div>
      <svg
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
      >
        <linearGradient
          gradientUnits="userSpaceOnUse"
          id="linear-gradient"
          x1="23.85"
          x2="23.85"
          y1="22.1"
          y2="40.01"
        >
          <stop offset="0.18" stopColor="#ff7b00" />
          <stop offset="1" stopColor="#ff7b00" />
        </linearGradient>
        <linearGradient
          gradientUnits="userSpaceOnUse"
          id="linear-gradient-2"
          x1="23.85"
          x2="23.85"
          y1="15.29"
          y2="22.38"
        >
          <stop offset="0.18" stopColor="#ff7b00" />
          <stop offset="1" stopColor="#ff7b00" />
        </linearGradient>
        <linearGradient
          id="linear-gradient-3"
          x1="23.77"
          x2="23.98"
          xlinkHref="#linear-gradient"
          y1="15.77"
          y2="23.75"
        />
        <linearGradient
          id="linear-gradient-4"
          x1="15.35"
          x2="15.35"
          xlinkHref="#linear-gradient"
          y1="37.24"
          y2="32.81"
        />
        <linearGradient
          id="linear-gradient-5"
          x1="21.35"
          x2="21.35"
          xlinkHref="#linear-gradient"
          y1="37.24"
          y2="32.81"
        />
        <linearGradient
          id="linear-gradient-6"
          x1="27.35"
          x2="27.35"
          xlinkHref="#linear-gradient"
          y1="37.24"
          y2="32.81"
        />
        <linearGradient
          id="linear-gradient-7"
          x1="33.35"
          x2="33.35"
          xlinkHref="#linear-gradient"
          y1="37.24"
          y2="32.81"
        />
        <linearGradient
          gradientUnits="userSpaceOnUse"
          id="linear-gradient-8"
          x1="15.35"
          x2="15.35"
          y1="27.48"
          y2="36.15"
        >
          <stop offset="0.18" stopColor="#8f6500" />
          <stop offset="1" stopColor="#774800" />
        </linearGradient>
        <linearGradient
          id="linear-gradient-9"
          x1="21.35"
          x2="21.35"
          xlinkHref="#linear-gradient-8"
          y1="27.48"
          y2="36.15"
        />
        <linearGradient
          id="linear-gradient-10"
          x1="27.35"
          x2="27.35"
          xlinkHref="#linear-gradient-8"
          y1="27.48"
          y2="36.15"
        />
        <linearGradient
          id="linear-gradient-11"
          x1="33.35"
          x2="33.35"
          xlinkHref="#linear-gradient-8"
          y1="27.48"
          y2="36.15"
        />
        <linearGradient
          gradientTransform="translate(-5.59 15.45) rotate(-45)"
          gradientUnits="userSpaceOnUse"
          id="linear-gradient-12"
          x1="14.74"
          x2="16.87"
          y1="13.36"
          y2="15.49"
        >
          <stop offset="0" stopColor="#4d4d4d" />
          <stop offset="0.18" stopColor="gray" />
          <stop offset="1" stopColor="#4d4d4d" />
        </linearGradient>
        <linearGradient
          gradientTransform="translate(44.14 47.23) rotate(-135)"
          id="linear-gradient-13"
          x1="32.92"
          x2="30.83"
          xlinkHref="#linear-gradient-12"
          y1="13.41"
          y2="15.5"
        />
        <g>
          <path
            fill="url(#linear-gradient)"
            d="M7.85,21.47h32a0,0,0,0,1,0,0v13a5,5,0,0,1-5,5h-22a5,5,0,0,1-5-5v-13A0,0,0,0,1,7.85,21.47Z"
          />
          <rect
            fill="url(#linear-gradient-2)"
            height="2"
            width="32"
            x="7.85"
            y="21.47"
          />
          <rect
            fill="url(#linear-gradient-3)"
            height="5"
            rx="2.5"
            ry="2.5"
            width="36"
            x="5.85"
            y="16.47"
          />
          <rect
            fill="url(#linear-gradient-4)"
            height="9"
            rx="1.5"
            ry="1.5"
            width="3"
            x="13.85"
            y="27.47"
          />
          <rect
            fill="url(#linear-gradient-5)"
            height="9"
            rx="1.5"
            ry="1.5"
            width="3"
            x="19.85"
            y="27.47"
          />
          <rect
            fill="url(#linear-gradient-6)"
            height="9"
            rx="1.5"
            ry="1.5"
            width="3"
            x="25.85"
            y="27.47"
          />
          <rect
            fill="url(#linear-gradient-7)"
            height="9"
            rx="1.5"
            ry="1.5"
            width="3"
            x="31.85"
            y="27.47"
          />
          <rect
            fill="url(#linear-gradient-8)"
            height="9"
            rx="1.5"
            ry="1.5"
            width="3"
            x="13.85"
            y="26.47"
          />
          <rect
            fill="url(#linear-gradient-9)"
            height="9"
            rx="1.5"
            ry="1.5"
            width="3"
            x="19.85"
            y="26.47"
          />
          <rect
            fill="url(#linear-gradient-10)"
            height="9"
            rx="1.5"
            ry="1.5"
            width="3"
            x="25.85"
            y="26.47"
          />
          <rect
            fill="url(#linear-gradient-11)"
            height="9"
            rx="1.5"
            ry="1.5"
            width="3"
            x="31.85"
            y="26.47"
          />
          <rect
            fill="url(#linear-gradient-12)"
            height="15.59"
            rx="1.5"
            ry="1.5"
            transform="translate(14.88 -6.97) rotate(45)"
            width="3"
            x="14.35"
            y="6.68"
          />
          <rect
            fill="url(#linear-gradient-13)"
            height="15.59"
            rx="1.5"
            ry="1.5"
            transform="translate(64.61 2.19) rotate(135)"
            width="3"
            x="30.35"
            y="6.68"
          />
        </g>
      </svg>
    </div>
  );
};

export default CartPic;
