export const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  UPDATE_PRODUCT_COUNT: "UPDATE_PRODUCT_COUNT",
  SET_CART_PRODUCTS: "SET_CART_PRODUCTS",
};
